# Source: jxl-boot/templates/install.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    release: jenkins-x
  name: jx-boot
spec:
  backoffLimit: 5
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        release: jenkins-x
    spec:
      containers:
      - args:
        - boot
        - run
        - -b
        - --git-url
        - "https://github.com/jenkins-x/jenkins-x-boot-helmfile-config.git"
        - --git-ref
        - "master"
        - --versions-repo
        - "https://github.com/jenkins-x-labs/jenkins-x-versions.git"
        - --versions-ref
        - "master"
        command:
        - jxl

        env:
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: JX_BATCH_MODE
          value: "true"
        - name: JX_LOG_FORMAT
          value: "json"

        - name: JX_HELM3
          value: "true"
        - name: JX_HELMFILE
          value: "true"
        - name: JX_SECRETS_YAML
          value: /secrets/jx-boot/secrets.yaml
        - name: JX_INTERPRET_PIPELINE
          value: "true"
        - name: JX_HOME
          value: /secrets
        image: "702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl:0.0.88"
        imagePullPolicy: IfNotPresent
        name: boot
      restartPolicy: Never
      serviceAccountName: jxl-boot
